# Generated by Django 4.2.4 on 2023-08-19 23:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alunos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('altura_em_cm', models.DecimalField(decimal_places=2, max_digits=5)),
                ('peso_em_kg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('dias_semana_objetivo', models.IntegerField(choices=[(1, '1 dia por semana'), (2, '2 dias por semana'), (3, '3 dias por semana'), (4, '4 dias por semana'), (5, '5 dias por semana'), (6, '6 dias por semana'), (7, 'Todos os dias')])),
                ('objetivo', models.CharField(choices=[('Emagrecimento', 'Emagrecimento'), ('Hipertrofia', 'Hipertrofia'), ('Reabilitação', 'Reabilitação'), ('Saúde', 'Saúde')], max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('utiliza_app', models.CharField(choices=[(1, 'Sim'), (2, 'Não')], max_length=1)),
            ],
        ),
    ]
