# Generated by Django 4.2.4 on 2023-08-20 13:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunosapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='altura_em_cm',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='peso_em_kg',
            field=models.PositiveIntegerField(),
        ),
        migrations.CreateModel(
            name='HistoricalAlunos',
            fields=[
                ('id', models.BigIntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('data_de_nascimento', models.DateField()),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], max_length=1)),
                ('altura_em_cm', models.PositiveIntegerField()),
                ('peso_em_kg', models.PositiveIntegerField()),
                ('dias_semana_objetivo', models.IntegerField(choices=[(1, '1 dia por semana'), (2, '2 dias por semana'), (3, '3 dias por semana'), (4, '4 dias por semana'), (5, '5 dias por semana'), (6, '6 dias por semana'), (7, 'Todos os dias')])),
                ('objetivo', models.CharField(choices=[('Emagrecimento', 'Emagrecimento'), ('Hipertrofia', 'Hipertrofia'), ('Reabilitação', 'Reabilitação'), ('Saúde', 'Saúde')], max_length=20, null=True)),
                ('celular', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=255)),
                ('utiliza_app', models.CharField(choices=[(1, 'Sim'), (2, 'Não')], max_length=1)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField(db_index=True)),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical alunos',
                'verbose_name_plural': 'historical alunoss',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': ('history_date', 'history_id'),
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
