# Generated by Django 4.2.4 on 2023-08-20 13:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('alunosapp', '0002_alter_alunos_altura_em_cm_alter_alunos_peso_em_kg_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alunos',
            name='utiliza_app',
        ),
        migrations.RemoveField(
            model_name='historicalalunos',
            name='utiliza_app',
        ),
        migrations.AddField(
            model_name='alunos',
            name='usa_aplicativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='historicalalunos',
            name='usa_aplicativo',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='historicalalunos',
            name='nome',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
