# Generated by Django 4.2.4 on 2023-08-20 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunosapp', '0003_remove_alunos_utiliza_app_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='historicalalunos',
            name='nome',
            field=models.CharField(max_length=100),
        ),
    ]
