# Generated by Django 4.2.4 on 2023-08-20 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunosapp', '0004_alter_alunos_nome_alter_historicalalunos_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='data_de_nascimento',
            field=models.DateField(help_text='Formato: dd/mm/aaaa', verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='historicalalunos',
            name='data_de_nascimento',
            field=models.DateField(help_text='Formato: dd/mm/aaaa', verbose_name='Data de Nascimento'),
        ),
    ]
