# Generated by Django 4.2.4 on 2023-08-20 13:44

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alunosapp', '0005_alter_alunos_data_de_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alunos',
            name='peso_em_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
        migrations.AlterField(
            model_name='historicalalunos',
            name='peso_em_kg',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
